import type { Metadata } from "next";
import "./globals.css";
import { JetBrains_Mono } from 'next/font/google'

const jetBrains = JetBrains_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={jetBrains.className}
      >
        {children}
      </body>
    </html>
  );
}
